development:
  dialect: "sqlite3"
  database: /home/joshwill300/project_database/lrn_lrn_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/joshwill300/project_database/lrn_lrn_test.sqlite

production:
  dialect: "sqlite3"
  database: /home/joshwill300/project_database/lrn_lrn_production.sqlite
